#!/usr/sbin/nft -f
# https://wiki.archlinux.org/title/nftables
flush ruleset;

# Interfaces
define if_priv = enp7s0;
define if_vpn_priv = sk01;
define if_vpn_open = sk02;

# IPs
define ip_self = { 192.168.4.2 };

# Subnets
define sub_lan = { 192.168.0.0/16 };
define sub_vpn_priv = { 10.70.31.0/25 };
define sub_vpn_open = { 10.70.31.128/25 };

table inet filter {
    chain input {
        type filter hook input priority 0;
        policy drop;

        # LO
        iif lo accept comment "LO: Accept all";

        # ALL
        ct state invalid drop comment "ALL: Drop invalid";
        ct state { established, related } accept comment "ALL: Allow established/related connections";
        meta l4proto icmp icmp type { echo-request, destination-unreachable, time-exceeded } limit rate 5/second counter accept comment "ALL: Accept select ICMP";

        # LAN
        iif { $if_priv } tcp dport { ssh } ip saddr { $sub_lan } ip daddr { $ip_self } accept comment "LAN: Accept on TCP";

        # VPN: Priv
        iifname { $if_vpn_priv } tcp dport { ssh } ip saddr { $sub_vpn_priv } ip daddr { $ip_self } accept comment "VPN (Priv): Accept on TCP";

        counter reject with icmpx type port-unreachable comment "Reject all other unsolicitated traffic";
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
