#!/bin/bash
set -e
#set -x

#######################################
#	Deploy dotfiles
#		./deploy locale
#	Arguments:
#		locale (string): set user locale to be deployed
#	Outputs:
#		None
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: ./deploy locale"

	if [[ "${#}" -ne 1 ]]; then
		.scripts/err "Error: one argument expected, ${#} received"
		.scripts/err "${USAGE}"
		return 1
	fi

	local readonly locale=${1}
	
	if [[ -z $(grep -v "#" /etc/locale.gen | grep "${locale}") ]]; then
		.scripts/err "Locale ${locale} does not exist"
		return 2
	fi

	for f in `find "$HOME/dotfiles/" -not -path "*/.git" -not -path "*/.git/*" -not -path "*/*.code-workspace" -not -path "*/.gitignore" -not -path "*/deploy"`; do		local from="${f}"
		local to=$(echo "${f}" | sed -r 's/\/dotfiles//')

		# If f is a dir, create it in ~
		[[ -d "${f}" ]] && mkdir -p "${to}" && continue

		# If f exists in ~, remove it
		[[ -f "${to}" ]] && rm -f "${to}"

		cp "${f}" "${to}"
	done

	# If device has a key, set it in .ssh/config, otherwise delete file (since it's useless in that case)
	if [[ -f "${HOME}/.ssh/${USER}@${HOSTNAME}.pub" ]]; then
		sed -i "s/privatekey/${USER}@${HOSTNAME}/g" "${HOME}/.ssh/config"
	else
		rm "${HOME}/.ssh/config"
	fi

	# Set correct shell config file
	local readonly my_shell=$(echo "${SHELL}" | rev | cut -d'/' -f1 | rev)

	# Create .profile
	echo -e "#!${SHELL}\n\n[[ \$- != *i* ]] && return\n\n. ~/.shrc\n" > "${HOME}/.${my_shell}rc"
	sed -i "s/MYSHELL/${my_shell}/g" "${HOME}/.profile"
	sed -i "s/MYSHELL/${my_shell}/g" "${HOME}/.shrc"
	sed -i "s/MYLOC/${locale}/g" "${HOME}/.profile"

	# Link .bashrc_profile to .profile
	[[ -f "${HOME}/.${my_shell}_profile" ]] && rm "${HOME}/.${my_shell}_profile"
	[[ ! -L "${HOME}/.${my_shell}_profile" ]] && ln -s "${HOME}/.profile" "${HOME}/.${my_shell}_profile"

	# Authorize my own device to access my device
	cat "${HOME}"/.ssh/*.pub > "${HOME}/.ssh/authorized_keys"

	return 0
}

main "${@}"; exit
