#!/bin/bash
set -e

#######################################
#	Deploy dotfiles
#		./deploy
#
#	Arguments:
#		None
#	Outputs:
#		None
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: ./deploy"

	if [[ "${#}" -ne 0 ]]; then
		.scripts/err "Error: no argument expected"
		.scripts/err "${USAGE}"
		return 1
	fi

	for f in `find "$HOME/dotfiles/" -not -path "*/.git/*" -not -path "*/*.code-workspace" -not -path "*/.gitignore" -not -path "*/deploy"`; do
		local from="${f}"
		local to=$(echo "${f}" | sed -r 's/\/dotfiles//')

		# If f is a dir, create it in ~
		[[ -d "${f}" ]] && mkdir -p "${to}" && continue

		# If f exists in ~, remove it
		[[ -f "${to}" ]] && rm -f "${to}"
		
		cp "${f}" "${to}"
	done

	# Update .ssh/config with local key
	if [[ -f "${HOME}/.ssh/${USER}@${HOSTNAME}.pub" ]]; then
		sed -i "s/privatekey/${USER}@${HOSTNAME}/g" "${HOME}/.ssh/config"
	else
		rm "${HOME}/.ssh/config"
	fi

	# Set correct shell config file
	local readonly my_shell=$(echo "${SHELL}" | rev | cut -d'/' -f1 | rev)

	echo -e "#!${SHELL}\n\n[[ \$- != *i* ]] && return\n\n# If available, load polyglot:\n[ -f ~/.polyglot.sh ] && . ~/.polyglot.sh\n\n. ~/.shrc\n" > "${HOME}/.${my_shell}rc"
	sed -i "s/MYSHELL/${my_shell}/g" "${HOME}/.profile"
	[[ -f "${HOME}/.${my_shell}_profile" ]] && rm "${HOME}/.${my_shell}_profile"
	[[ ! -L "${HOME}/.${my_shell}_profile" ]] && ln -s "${HOME}/.profile" "${HOME}/.${my_shell}_profile"

	return 0
}

main "${@}"; exit
