#!/bin/bash
set -e

#######################################
#	Deploy dotfiles
#		./deploy
#
#	Arguments:
#		None
#	Outputs:
#		None
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: ./deploy"

	if [[ "${#}" -ne 0 ]]; then
		.scripts/err "Error: no argument expected"
		.scripts/err "${USAGE}"
		return 1
	fi

	for f in `find . -type f -not -path "./.git/*" -not -path "./deploy" -not -path "./.gitignore" | cut -c3-`; do
		# Only remove files (so we don't delete ~/.config by accident)
		[[ -f "${HOME}/${f}" ]] && rm "${HOME}/${f}"

		# If dir exists in dotfiles but not in ~ => create it
		[[ -d ${f%/*} ]] && [[ ! -d "${HOME}/${f%/*}" ]] && mkdir "${HOME}/${f%/*}"

		cp "${f}" "${HOME}/${f}"
	done

	# Create link ~/.bash_profile -> ~/.profile
	if [[ ! -f ~/.bash_profile ]]; then
		ln -s ~/.profile ~/.bash_profile
	fi

	# Update .ssh/config with local key
	if [[ -f "${HOME}/.ssh/${USER}@${HOSTNAME}.pub" ]]; then
		sed -i "s/privatekey/${USER}@${HOSTNAME}/g" ~/.ssh/config
	else
		rm ~/.ssh/config
	fi

	return 0
}

main "${@}"; exit
