# Private LAN

Host *.home.karlsen.fr
    User                sebastian

## Debian gateway: nftables, dhcpd
Host helios.home.karlsen.fr
    #Hostname           helios
    Hostname            192.168.4.1


## enp2s0 (192.168.2.0/24): WAP, laptops, phones

### NetGear RAX80
Host rax80.home.karlsen.fr
    Hostname           rax80
    #Hostname            192.168.2.2

### xps13
Host xps13.home.karlsen.fr
    Hostname            xps13
    #Hostname            192.168.2.3

### fjordmail-xps15 - Work PC
Host fjordmail-xps15.home.karlsen.fr
    Hostname            fjordmail-xps15
    #Hostname            192.168.2.4

### xperia5ii - Phone
Host xperia5ii.home.karlsen.fr
    Hostname            xperia5ii
    #Hostname            192.168.2.5

### sk-g990b - Phone
Host sk-g990b.home.karlsen.fr
    Hostname            sk-g990b
    #Hostname            192.168.2.5


## enp3s0 (192.168.3.0/24): RBP4

### Raspberry Pi - Pihole
Host hermes.home.karlsen.fr
    Hostname           hermes
    #Hostname            192.168.3.2


## enp4s0 (192.168.4.0/24): Desktop

### Aorus desktop
Host zeus.home.karlsen.fr
    Hostname           zeus
    #Hostname            192.168.4.2


## enp5s0 (192.168.5.0/24): VM machine

### Dell Poweredge T420
Host atlas.home.karlsen.fr
   Hostname            atlas
   #Hostname             192.168.5.2


## enp6s0 (192.168.6.0/24): NAS

### SuperMicro NixOS NAS
Host chronos.home.karlsen.fr
   Hostname            chronos
   #Hostname             192.168.6.2