## DigitalOcean / Karlsen Sandbox

Host gw01.fra1-01.do.karlsen.fr
    Hostname 138.197.179.209
Host cp01.testcluster.fra1-01.do.karlsen.fr
    Hostname 167.71.58.58
Host w01.testcluster.fra1-01.do.karlsen.fr
    Hostname 167.71.50.50
Host w02.testcluster.fra1-01.do.karlsen.fr
    Hostname 138.197.185.111
Host w03.testcluster.fra1-01.do.karlsen.fr
    Hostname 167.71.45.100