# Private LAN - Proxmox VE

Host *.home.karlsen.fr
    User                sebastian

### Proxy (Traefik)
Host proxy.atlas.home.karlsen.fr
    Hostname           proxy.atlas.home.karlsen.fr
    #Hostname          192.168.5.3

### Database server (MariaDB)
Host db.atlas.home.karlsen.fr
    Hostname           db.atlas.home.karlsen.fr
    #Hostname          192.168.5.4

### Kubernetes Control Plane
Host kc.atlas.home.karlsen.fr
    Hostname           kc.atlas.home.karlsen.fr
    #Hostname          192.168.5.5

### Kubernetes Node 1
Host kn1.atlas.home.karlsen.fr
    Hostname           kn1.atlas.home.karlsen.fr
    #Hostname          192.168.5.6
