# Private LAN - Proxmox VE

Host *.home.karlsen.fr
    User                sebastian

### Docker Swarm Manager files
Host manager.atlas.home.karlsen.fr
    Hostname           manager.atlas.home.karlsen.fr
    #Hostname          192.168.5.3

### Arch test machine
Host archlinux.atlas.home.karlsen.fr
    Hostname           archlinux.atlas.home.karlsen.fr
    #Hostname          192.168.5.4

### Windows 11
Host janus.atlas.home.karlsen.fr
    Hostname           janus.atlas.home.karlsen.fr
    #Hostname          192.168.5.5

### Swarm Node 1
Host n1.atlas.home.karlsen.fr
    Hostname           n1.atlas.home.karlsen.fr
    #Hostname          192.168.5.6

# Temp file server (before moving to chronos - supermicro NAS)
Host file.atlas.home.karlsen.fr
    Hostname           file.atlas.home.karlsen.fr
    #Hostname          192.168.5.7

# Public proxy
Host prx01.atlas.home.karlsen.fr
    Hostname           prx01.atlas.home.karlsen.fr
    #Hostname          192.168.5.8

### Windows XP
Host xp.atlas.home.karlsen.fr
    Hostname           xp.atlas.home.karlsen.fr
    #Hostname          192.168.5.9

### Torrent files
Host torrent.atlas.home.karlsen.fr
    Hostname           torrent.atlas.home.karlsen.fr
    #Hostname          192.168.5.10

### Swarm Node 2
Host n2.atlas.home.karlsen.fr
    Hostname           n2.atlas.home.karlsen.fr
    #Hostname          192.168.5.11

# Private proxy
Host prx02.atlas.home.karlsen.fr
    Hostname           prx02.atlas.home.karlsen.fr
    #Hostname          192.168.5.12

