# Private LAN - Proxmox VE

Host *.home.karlsen.fr
    User                sebastian

# Archlinux LXC
Host archlinux.atlas.home.karlsen.fr
    Hostname           archlinux.atlas.home.karlsen.fr
    #Hostname          192.168.5.4

### Windows 11
Host janus.atlas.home.karlsen.fr
    Hostname           janus.atlas.home.karlsen.fr
    #Hostname          192.168.5.5

### Windows XP
Host xp.atlas.home.karlsen.fr
    Hostname           xp.atlas.home.karlsen.fr
    #Hostname          192.168.5.9

# Temp file server (before moving to chronos - supermicro NAS)
Host file.atlas.home.karlsen.fr
    Hostname           file.atlas.home.karlsen.fr
    #Hostname          192.168.5.7

# Torrent nsf file server
Host torrent.atlas.home.karlsen.fr
    Hostname           torrent.atlas.home.karlsen.fr
    #Hostname          192.168.5.10

# prx01 - Public services
Host prx01.atlas.home.karlsen.fr
    #Hostname         prx01.atlas.home.karlsen.fr
    Hostname          192.168.5.8

# prx02 - Private services
Host prx02.atlas.home.karlsen.fr
    #Hostname         prx02.atlas.home.karlsen.fr
    Hostname          192.168.5.12
