Host *.fjordmail.no
    User                fjordmail

## Monitor (Checkmk)
Host monitor.fjordmail.no
    Hostname            46.101.211.155
    Port                39447

## Backup of Deploi services
Host backup.fjordmail.no
    Hostname            46.101.197.132
    Port                39456
