Host *.fjordmail.no
    User                fjordmail

## Gateway
Host gw01.mc.fjordmail.no
    #Hostname            81.7.169.166
    Hostname            172.16.50.210
    #Hostname            100.104.5.43

# prx11
Host prx11.fjordmail.no
    #Hostname           81.7.169.246
    Hostname            172.16.50.221

# prx12
Host prx12.fjordmail.no
    #Hostname           81.7.169.247
    Hostname            172.16.50.222

## Backend srv 11
Host be11.fjordmail.no
    Hostname            172.16.50.21

## Backend srv 12
Host be12.fjordmail.no
    Hostname            172.16.50.22

## Backend srv 13
Host be13.fjordmail.no
    Hostname            172.16.50.23

## Backend srv 14
Host be14.fjordmail.no
    Hostname            172.16.50.24

## Backend srv 15
Host be15.fjordmail.no
    Hostname            172.16.50.25

## Backend srv 16
Host be16.fjordmail.no
    Hostname            172.16.50.26

## Backend srv 17
Host be17.fjordmail.no
    Hostname            172.16.50.27

## Backend srv 18
Host be18.fjordmail.no
    Hostname            172.16.50.28

## Backend srv 19
Host be19.fjordmail.no
    Hostname            172.16.50.29

## File server
Host data01.fjordmail.no
    Hostname            172.16.50.150

## DB server db10 (webmails)
Host db10.fjordmail.no
    Hostname            172.16.50.100

## DB server db20 (api)
Host db20.fjordmail.no
    Hostname            172.16.50.120

## API srv 02
Host api02.fjordmail.no
    #Hostname           81.7.169.168
    Hostname            172.16.50.251

## redis srv
Host redis01.fjordmail.no
    Hostname            172.16.50.220

# MC Cluster
Host n1.mcswarm.mc.fjordmail.no
    Hostname            172.16.50.81
    #Hostname            81.7.169.214
Host n2.mcswarm.mc.fjordmail.no
    Hostname            127.0.0.1
Host n3.mcswarm.mc.fjordmail.no
    Hostname            127.0.0.1

# To be removed

## API srv 01
Host api01.fjordmail.no
    #Hostname           81.7.169.168
    Hostname            172.16.50.250
