Host *.fjordmail.no
    User                fjordmail

## Prod env for frontpages
Host prod.fjordmail.no
    Hostname            193.69.47.233
    Port                39469

## Multisite WP for Luukku etc.
Host wp.fjordmail.no
    Hostname            193.69.47.111
    Port                39274

## fjordmail-admin
Host wp3.fjordmail.no
    Hostname            193.69.47.245
    Port                39453

## test env
Host test.fjordmail.no
    Hostname            193.69.50.104

## dev env
Host dev.fjordmail.no
    Hostname            193.69.47.227

## staging env
Host staging.fjordmail.no
    Hostname            193.69.47.51

## cms.fjordmail.no
Host cms.fjordmail.no
    Hostname            193.69.47.186

## Wemail WP - To be moved to fjordmail-wp
Host wemail.no-WP
    Hostname            193.69.47.29
    User                root

## Fjordmail.com WP - To be moved to fjordmail-wp
Host FjordmailWP
    Hostname            193.69.47.109
    User                root

# TO DELETE

## Old API
Host api.old.fjordmail.no
    Hostname            193.69.47.3
    Port                39546

# Grav sites
Host grav.fjordmail.no
    Hostname            193.69.50.100

## Webmail on secure.fjordmail.com
Host secure.fjordmail.com
    Hostname            193.69.47.116
    Port                58022
    User                root

