Host *.fjordmail.no
    User                fjordmail

## Gateways
Host gw01.fra1-01.do.fjordmail.no
    #Hostname            138.68.101.140
    Hostname            10.114.16.6
    #Hostname            100.65.89.84

## Headscale control
Host hs01.fra1-01.do.fjordmail.no
    #Hostname            157.230.127.187
    Hostname            10.114.16.12

## Monitor
Host n1.domonitor.fra1-01.do.fjordmail.no
    #Hostname            165.22.89.3
    Hostname            10.114.16.7
Host n2.domonitor.fra1-01.do.fjordmail.no
    #Hostname            167.172.168.100
    Hostname            10.114.16.8

## Authswarm
Host n1.authswarm.fra1-01.do.fjordmail.no
    #Hostname            139.59.147.170
    Hostname            10.114.16.2
Host n2.authswarm.fra1-01.do.fjordmail.no
    #Hostname            159.223.23.82
    Hostname            10.114.16.3
Host n3.authswarm.fra1-01.do.fjordmail.no
    #Hostname            164.90.183.119
    Hostname            10.114.16.4

## Sandbox: webmails, fmapi, fmadmin, strapi/next websites
Host n1.sandbox.fra1-01.do.fjordmail.no
    #Hostname            207.154.230.190
    Hostname           10.114.16.9
Host n2.sandbox.fra1-01.do.fjordmail.no
    #Hostname            64.226.86.83
    Hostname           10.114.16.10
Host n3.sandbox.fra1-01.do.fjordmail.no
    #Hostname            64.226.86.95
    Hostname           10.114.16.11

## Supportswarm
#Host n1.supportswarm.fra1-01.do.fjordmail.no
#    Hostname            
#Host n2.supportswarm.fra1-01.do.fjordmail.no
#    Hostname            
#Host n3.supportswarm.fra1-01.do.fjordmail.no
#    Hostname            

##
## To be moved to VPC
##

## Webswarm - Production
Host n1.webswarm.fjordmail.no
    Hostname            167.71.40.43
Host n2.webswarm.fjordmail.no
    Hostname            104.248.247.215
Host n3.webswarm.fjordmail.no
    Hostname            104.248.247.66

## Sandbox: webswarm + rcswarm
Host n1.sandbox.fjordmail.no
    Hostname            164.92.241.161
Host n2.sandbox.fjordmail.no
    Hostname            167.71.40.146
Host n3.sandbox.fjordmail.no
    Hostname            46.101.151.95