Host *.fjordmail.no
    User                fjordmail

## VPN (wg)
Host vpn01.fjordmail.no
    #Hostname           81.7.169.166
    Hostname            172.16.50.210

## Load balancer
Host prx01.fjordmail.no
    #Hostname           81.7.169.165
    Hostname            172.16.50.200

## Load balancer
Host prx02.fjordmail.no
    #Hostname           81.7.169.206
    Hostname            172.16.50.201

# New prx11
Host prx11.fjordmail.no
    #Hostname           81.7.169.246
    Hostname            172.16.50.221

## File server
Host data01.fjordmail.no
    Hostname            172.16.50.150

## DB server db10 (webmails)
Host db10.fjordmail.no
    Hostname            172.16.50.100

## DB server db20 (api)
Host db20.fjordmail.no
    Hostname            172.16.50.120

## Backend srv 01
Host be01.fjordmail.no
    Hostname            172.16.50.11

## Backend srv 02
Host be02.fjordmail.no
    Hostname            172.16.50.12

## Backend srv 03
Host be03.fjordmail.no
    Hostname            172.16.50.13

## Backend srv 04
Host be04.fjordmail.no
    Hostname            172.16.50.14

## Backend srv 05
Host be05.fjordmail.no
    Hostname            172.16.50.15

## Backend srv 06
Host be06.fjordmail.no
    Hostname            172.16.50.16
## New backend srv 11
Host be11.fjordmail.no
    Hostname            172.16.50.21

## New backend srv 12
Host be12.fjordmail.no
    Hostname            172.16.50.22

## New backend srv 13
Host be13.fjordmail.no
    Hostname            172.16.50.23

## New backend srv 14
Host be14.fjordmail.no
    Hostname            172.16.50.24

## New backend srv 15
Host be15.fjordmail.no
    Hostname            172.16.50.25

## New backend srv 16
Host be16.fjordmail.no
    Hostname            172.16.50.26

## API srv 01
Host api01.fjordmail.no
    #Hostname           81.7.169.168
    Hostname            172.16.50.250

## API srv 02
Host api02.fjordmail.no
    #Hostname           81.7.169.168
    Hostname            172.16.50.251

## redis srv
Host redis01.fjordmail.no
    Hostname            172.16.50.220
