Host *.fjordmail.no
    User                fjordmail

## Monitor (Uptime Kuma, librenms...)
Host n1.monitor.fjordmail.no
    Hostname 193.69.47.227

# Avbestilt

Host test.fjordmail.no
    Hostname            193.69.50.104
Host prod.fjordmail.no
    Hostname            193.69.47.233
    Port                39469
Host wp.fjordmail.no
    Hostname            193.69.47.111
    Port                39274
Host wp3.fjordmail.no
    Hostname            193.69.47.245
    Port                39453
Host wemail.no-WP
    Hostname            193.69.47.29
    User                root
Host FjordmailWP
    Hostname            193.69.47.109
    User                root
Host cms.fjordmail.no
    Hostname            193.69.47.186
