Host *.fjordmail.no
    User                fjordmail

## Webswarm - Production
Host n1.webswarm.fjordmail.no
    Hostname            167.71.40.43
Host n2.webswarm.fjordmail.no
    Hostname            104.248.247.215
Host n3.webswarm.fjordmail.no
    Hostname            104.248.247.66

## Sandbox: webswarm + rcswarm
Host n1.sandbox.fjordmail.no
    Hostname            164.92.241.161
Host n2.sandbox.fjordmail.no
    Hostname            167.71.40.146
Host n3.sandbox.fjordmail.no
    Hostname            46.101.151.95

## Supportswarm (Chatwoot)
Host n1.supportswarm.fjordmail.no
    Hostname            139.59.143.193
Host n2.supportswarm.fjordmail.no
    Hostname            104.248.252.160
Host n3.supportswarm.fjordmail.no
    Hostname            164.92.244.3

## Backup
Host backup.fjordmail.no
    Hostname            46.101.197.132
