#!/bin/sh -e
# Generate aliases for uutils: https://github.com/uutils/coreutils/

dest=~/.sh/uutils_aliases
if [ -f $dest ]; then
	rm $dest
fi

echo '#!'"/bin/sh" >> $dest
for f in $(command ls /usr/bin/uu-*); do
	echo "alias $(basename $f | cut -d- -f2)=$f" >> $dest
done;

exit 0
