#!/bin/sh -e
# Extract Win10 fonts for https://aur.archlinux.org/packages/ttf-ms-win10/

USAGE="Usage: getFonts [iso]"

# Does wimextract command exist?
if ! [ -x "$(command -v wimextract)" ]; then
	echo "Error: wimextract command not found. Please install wimlib"
	exit 1
fi

# If iso provided, does the file exist? If not, fetch it
if [ "$#" -eq 1 ] && [ -f "$1" ]; then
	FILE=$1
elif [ "$#" -eq 1 ] && [ ! -f "$1" ]; then
	echo "Error: file '$1' not found"
	echo "$USAGE"
	exit 1
else
	FILE="win.iso"

	if getWin "English" "$FILE"; then
		echo "Download OK"
	else
		echo "Download of ISO failed! Please try again"
		exit 1
	fi;
fi

# Extract fonts from iso
mkdir iso
sudo mount $FILE iso -o loop
wimextract iso/sources/install.wim 1 /Windows/{Fonts/"*".{ttf,ttc},System32/Licenses/neutral/"*"/"*"/license.rtf} --dest-dir fonts
sudo umount iso
rmdir iso

# Remove iso if it has not been provided as an argument
if [ "$#" -eq 0 ]; then
	rm $FILE
fi

# If build folder is found, copy fonts to it
if [ -d ~/.cache/paru/clone/ttf-ms-win10/ ]; then
	cp fonts/* ~/.cache/paru/clone/ttf-ms-win10/
elif [ -d ~/.cache/yay/clone/ttf-ms-win10/ ]; then
	cp fonts/* ~/.cache/yay/clone/ttf-ms-win10/
fi

exit 0
