#!/bin/sh -e
# Download Win10 ISO (Inspired from https://gist.github.com/hongkongkiwi/15a5bf16437315df256c118c163607cb)
# https://tb.rg-adguard.net/public.php
# https://www.microsoft.com/en-us/software-download/windows10ISO

USAGE="Usage: getWin [language [output]]"

# Check args
if [ "$#" -lt 0 ] || [ "$#" -gt 2 ]; then
	echo "Error: at most two positional arguments"
	echo "$USAGE"
	exit 1
fi

if [ "$#" -eq 0 ] || [ -z "$1" ]; then
	LANG_NAME="English"
else
	LANG_NAME=$1
fi

if [ "$#" -eq 2 ] && [ -z "$2" ]; then
	echo "Error: output file cannot be an empty string"
	echo "$USAGE"
	exit 1
fi

# Get file info
ARCH="x64"
LATEST_WINDOWS_VERSION=`curl -s -H "Accept: application/json" "https://tb.rg-adguard.net/php/get_version.php?type_id=1" | jq '.versions | sort_by(-(.version_id | tonumber))[0]'`
WINDOWS_NAME=`echo "$LATEST_WINDOWS_VERSION" | jq -r .name`
VERSION_ID=`echo "$LATEST_WINDOWS_VERSION" | jq -r .version_id`
EDITION_ID=`curl -s -H "Accept: application/json" "https://tb.rg-adguard.net/php/get_edition.php?version_id=${VERSION_ID}&lang=name_en" | jq -r '.editions[] | select(.name_en=="Windows 10").edition_id'`
LANGUAGE_ID=`curl -s -H "Accept: application/json" "https://tb.rg-adguard.net/php/get_language.php?edition_id=${EDITION_ID}&lang=name_en" | jq -r '.languages[] | select(.name_en=="'${LANG_NAME}'").language_id'`
ARCH_INFO=`curl -s -H "Accept: application/json" "https://tb.rg-adguard.net/php/get_arch.php?language_id=${LANGUAGE_ID}"`
FILE_NAME=`echo "$ARCH_INFO" | jq -r '.archs[] | select(.name | contains("'${ARCH}'")).name'`
ARCH_ID=`echo "$ARCH_INFO" | jq -r '.archs[] | select(.name | contains("'${ARCH}'")).arch_id'`
DOWNLOAD_INFO=`curl -s "https://tb.rg-adguard.net/dl.php?fileName=${ARCH_ID}&lang=en"`
DOWNLOAD_ID=`echo "$DOWNLOAD_INFO" | grep -oP '(?<=https:\/\/tb\.rg-adguard\.net/dl\.php\?go=)[0-9a-z]+'`
DOWNLOAD_URL="https://tb.rg-adguard.net/dl.php?go=${DOWNLOAD_ID}"
FILE_SIZE_MB=`echo "$DOWNLOAD_INFO" | grep -oP "(?<=File size: </b>)[0-9.]+"`
FILE_SIZE_BYTES=`echo "$DOWNLOAD_INFO" | grep -oP "(?<=File size: </b>)[0-9(). A-Z]+" | cut -d "(" -f2 | tr -d ' '`

# If at least one var i empty, abort
if [ -z "$WINDOWS_NAME" ] || [ -z "$VERSION_ID" ] || [ -z "$EDITION_ID" ] || [ -z "$LANGUAGE_ID" ] || [ -z "$ARCH_INFO" ] || [ -z "$FILE_NAME" ] || [ -z "$ARCH_ID" ] || [ -z "$DOWNLOAD_INFO" ] || [ -z "$DOWNLOAD_ID" ] || [ -z "$DOWNLOAD_URL" ] || [ -z "$FILE_SIZE_MB" ] || [ -z "$FILE_SIZE_BYTES" ]; then
	echo "Error: file not found"
	exit 1
fi

echo "Found $WINDOWS_NAME"
if [ -f "$FILE_NAME" ]; then
	EXISTING_BYTES=`stat --printf="%s" "$FILE_NAME"`

	if [ "$EXISTING_BYTES" -eq "$FILE_SIZE_BYTES" ]; then
		echo "File already exists! Skipping download"
		exit 0
	else
		echo "File does exist but has wrong bytesize! (got $EXISTING_BYTES expected $FILE_SIZE_BYTES)"
		echo "Probably corrupt or incomplete - removing"
		rm "$FILE_NAME"
	fi
fi

echo "Downloading $FILE_NAME ($FILE_SIZE_MB MB [$FILE_SIZE_BYTES bytes])"

# If second arg is provided, store file to $2
if [ "$#" -eq 2 ]; then
	FILE_NAME="$2"
fi

# Download file
curl -s -L "$DOWNLOAD_URL" -o "$FILE_NAME"

# Checksum
shasum=`sha1sum "$FILE_NAME" | cut -d " " -f1`

if curl -s https://sha1.rg-adguard.net/search.php?sha1="$shasum" | grep -q "<b>It is found in  msdn.rg-adguard.net:</b> 1"; then
	echo "Checkum OK"
else
	echo "Cheksum failed! Please try again"
	rm "$FILE_NAME"
	exit 1
fi

exit 0
