#!/bin/bash -e
# Set a sudo lecturer

USAGE="Usage: set_lecturer lecturer"

# Groot: https://caferock.org/chris/groot.txt || https://www.cyberciti.biz/files/groot.txt
# Dinosaurus: https://caferock.org/chris/dinosaurus.txt
# Tradewars: https://caferock.org/chris/tradewars.txt
declare -a lecturers=("groot" "dinosaurus" "tradewars" "none")

if [ "$#" -lt 1 ]; then
	echo "Error: no argument provided"
	echo "$USAGE"
	exit 1
fi

# It's easy to check if an array contains an element in bash
if [[ ! ${lecturers[*]} =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
	echo "Error: invalid argument provided"
	echo "Available lecturers:"
	printf '\t%s\n' "${lecturers[@]}"
	exit 1
fi

if [ -f /etc/sudoers.d/lecturer.txt ]; then
	sudo rm /etc/sudoers.d/lecturer.txt
fi

if [ -f /etc/sudoers.d/lecture ]; then
	sudo rm /etc/sudoers.d/lecture
fi

# Quit now if resetting the lecturer
if [ $1 == "none" ]; then
	exit 0
fi

# Quit if missing file in ~/.sh/
if [ ! -f ~/.sh/"$1".txt ] || [ ! -f ~/.sh/lecture ]; then
	echo "Missing lecturer file in ~/.sh/"
	exit 1
fi

# Copy files to /etc/sudoers.d/ and give correct permissions
sudo cp ~/.sh/"$1".txt /etc/sudoers.d/lecturer.txt
sudo cp ~/.sh/lecture /etc/sudoers.d/lecture

sudo chmod 0440 /etc/sudoers.d/lecturer.txt
sudo chmod 0440 /etc/sudoers.d/lecture

# Reset sudo so the new lecturer can be tested
sudo --reset-timestamp

exit 0
