#!/bin/bash
set -e

#######################################
#	Generate aliases for uutils: https://github.com/uutils/coreutils/
#	Creates file with aliases: ~/.scripts/uutils_aliases and then removes it
#		gen_uutils
#
#	Arguments:
#		None
#	Outputs:
#		None
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: gen_uutils"
	local readonly dest=~/.uutils_aliases

	if [[ "${#}" -ne 0 ]]; then
		err "Error: no argument required"
		err "${USAGE}"
		return 1
	fi

	# Remove file if it exists
	if [[ -f "${dest}" ]]; then
		rm "${dest}"
	fi

	# Rust coreutils not installed -> exit without error
	if ! command ls /usr/bin/uu-*; then
		return 0
	fi

	# Create alias for each /usr/bin/uu- binary
	echo '#!'"/bin/sh" > "${dest}"
	for f in $(command ls /usr/bin/uu-*); do
		echo "alias $(basename ${f} | cut -d- -f2)=${f}" >> "${dest}"
	done;

	return 0
}

main "${@}"; exit
