#!/bin/bash
set -e
#set -x

#######################################
#	Generate aliases for uutils: https://github.com/uutils/coreutils/
#	Creates file with aliases: ~/.scripts/uutils_aliases and then removes it
#		gen_uutils
#
#	Arguments:
#		None
#	Outputs:
#		None
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: gen_uutils"
	local readonly dest=~/.uutils_aliases

	if [[ "${#}" -ne 0 ]]; then
		err "Error: no argument expected, ${#} received"
		err "${USAGE}"
		return 1
	fi

	# Remove file if it exists
	if [[ -f "${dest}" ]]; then
		rm "${dest}"
	fi

	# Create alias for each /usr/bin/uu- binary
	for f in /usr/bin/uu-*; do
		if [[ -f "${f}" ]]; then # Prevent "alias *=/usr/bin/uu-*"
			echo "alias $(basename ${f} | cut -d- -f2)=${f}" >> "${dest}"
		fi
	done;

	# If no line has been printed to $dest, quit with err
	if [[ ! -f "${dest}" ]]; then
		return 1
	fi

	return 0
}

main "${@}"; exit
