#!/bin/bash
set -e

#######################################
#	Fetch or update to latest polyglot
#		get_polyglot
#
#	Arguments:
#		None
#	Outputs:
#		Diff
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: get_polyglot"

	if [[ "${#}" -ne 0 ]]; then
		err "Error: no argument expected, ${#} received"
		err "${USAGE}"
		return 1
	fi

	# Check if diff command is available
	if [[ ! -x "$(command -v diff)" ]]; then
                err "Error: diff command not found. Please install diffutils"
                return 1
        fi

	# Make sure output file does not exist and fetch new polyglot
	[[ -f ~/.polyglot.new ]] && rm ~/.polyglot.new
	curl -o ~/.polyglot.new https://raw.githubusercontent.com/agkozak/polyglot/master/polyglot.sh

	# Show diff
	if [[ ! -f ~/.polyglot.sh ]]; then
		cat ~/.polyglot.new
	elif diff ~/.polyglot.sh ~/.polyglot.new; then
		echo "No difference between new and old file!"
		rm ~/.polyglot.new
		return 0
	fi

	# Prompt the user for yes/no
	while true; do
		local yn=""
		read -p "Set new polyglot? [y/n] " yn
		case $yn in
			[Yy]* ) break;;
			[Nn]* ) rm ~/.polyglot.new && return 0;;
			* ) echo "Please answer yes or no.";;
		esac
	done

	# Set new
	[[ -f ~/.polyglot.sh ]] && rm ~/.polyglot.sh
	mv ~/.polyglot.new ~/.polyglot.sh

	return 0
}

main "${@}"; exit

