#!/bin/bash
set -e

#######################################
#	Run projects built with kdesrc-build
#		kdesrc-run
#
#	Arguments:
#		None
#	Outputs:
#		Build output
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: kdesrc-run"

	if [[ "${#}" -ne 0 ]]; then
		err "Error: no argument required"
		err "${USAGE}"
		return 1
	fi

	# If ~/kde/src/ does not exist, quit
	if [ ! -d ~/kde/src/ ]; then
		return 1
	fi

	. "${HOME}/kde/build/${1}/prefix.sh" && "${HOME}/kde/usr/bin/${1##*/}" "${@:2:$#}"

	return 0
}

main "${@}"; exit
