#!/bin/bash
set -e
#set -x

#######################################
#	Create new client for OpenVPN server
#		openvpn_new_client remote_IP remote_port client_name
#	Arguments:
#		remote_IP (string): server's remote IP or hostname
#		remote_port (int): servers's openvpn extenal port
#		client_name (string): client's name
#	Outputs:
#		Crt, key and .ovpn files
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: openvpn_new_client remote_IP remote_port client_name"

	if [[ "${#}" -ne 3 ]]; then
		err "Error: two argument expected, ${#} received"
		err "${USAGE}"
		return 1
	fi

	local readonly remote_IP="${1}"
	local readonly remote_port="${2}"
	local readonly client_name="${3}"

	if [ "${EUID}" -ne 0 ]; then
		err "Please run as root"
		return 2
	fi

	if [[ ! -z $(find /etc/openvpn/ | grep $client_name) ]]; then
		err "There already is a client named ${client_name}"
		err "Please use another name"
		return 3
	fi

	# Set env
	[[ -z "${EASYRSA}" ]] && export EASYRSA=/etc/easy-rsa
	[[ -z "${EASYRSA_VARS_FILE}" ]] && export EASYRSA_VARS_FILE=/etc/easy-rsa/vars

	if [[ ! -d "${EASYRSA}" ]] || [[ ! -f "${EASYRSA_VARS_FILE}" ]] || [[ ! -x "$(command -v easyrsa)" ]]; then
		err "Please install EasyRSA in ${EASYRSA}"
		return 4
	fi

	# Create client key and cert
	easyrsa gen-req "${client_name}" nopass
	easyrsa sign-req client "${client_name}"

	# Move to /etc/openvpn
	cp "/etc/easy-rsa/pki/private/${client_name}.key" /etc/openvpn/client/
	cp "/etc/easy-rsa/pki/issued/${client_name}.crt" /etc/openvpn/client/

	# Create client.ovpn file
	echo "${config}" | sed "s/REMOTE_IP/${remote_IP}/g" \
		| sed "s/REMOTE_PORT/${remote_port}/g" \
		| sed '/<ca>/r /etc/openvpn/server/ca.crt' \
		| sed "/<cert>/r /etc/openvpn/client/$client_name.crt" \
		| sed "/<key>/r /etc/openvpn/client/$client_name.key" \
		| sed '/<tls-crypt>/r /etc/openvpn/server/ta.key' \
		> "/etc/openvpn/client/${client_name}.ovpn"

	mkdir -p /etc/openvpn/revoked/
	chown -R openvpn:network /etc/openvpn/server/ /etc/openvpn/client/ /etc/openvpn/revoked/

	return 0
}

readonly config="# OpenVPN client config

client
dev tun
remote REMOTE_IP REMOTE_PORT udp
resolv-retry infinite
nobind
persist-key
persist-tun
verb 4

auth SHA512
auth-nocache
cipher AES-256-GCM

tls-client
tls-version-min 1.3
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256

remote-cert-tls server

route-nopull
route 10.7.0.0 255.255.255.0
dhcp-option DNS 10.7.0.2

###
###     Keys and certificates
###

# Server cert (ca.crt)
<ca>
</ca>

# Client cert (client.crt)
<cert>
</cert>

# Client key (client.key)
<key>
</key>

# Shared-secret key (ta.key)
<tls-crypt>
</tls-crypt>
"

main "${@}"; exit
