#!/bin/bash
set -e

#######################################
#	Create new client for OpenVPN server
#		openvpn_new_client remote_IP client_name
#	Arguments:
#		remote_IP (string): server's remote IP or hostname
#		client_name (string): client's name
#	Outputs:
#		Crt, key and .ovpn files
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: openvpn_new_client remote_IP client_name"

	if [[ "${#}" -ne 2 ]]; then
		err "Error: two argument expected, ${#} received"
		err "${USAGE}"
		return 1
	fi

	local readonly remote_IP="${1}"
	local readonly client_name="${2}"

	if [ "${EUID}" -ne 0 ]; then
		err "Please run as root"
		return 2
	fi

	if [[ -f "/etc/openvpn/client/${client_name}.crt" ]] || [[ -f "/etc/openvpn/client/${client_name}.key" ]] || [[ -f "/etc/openvpn/client/${client_name}.ovpn" ]]; then
		err "There already is a client named ${client_name}"
		err "Please use another name"
		return 3
	fi

	# Set env
	[[ -z "${EASYRSA}" ]] && export EASYRSA=/etc/easy-rsa
	[[ -z "${EASYRSA_VARS_FILE}" ]] && export EASYRSA_VARS_FILE=/etc/easy-rsa/vars

	if [[ ! -d "${EASYRSA}" ]] || [[ ! -f "${EASYRSA_VARS_FILE}" ]] || [[ ! -x "$(command -v easyrsa)" ]]; then
		err "Please install EasyRSA in ${EASYRSA}"
		return 4
	fi

	# Create client key and cert
	easyrsa gen-req "${client_name}" nopass
	easyrsa sign-req client "${client_name}"

	# Move to /etc/openvpn
	cp "/etc/easy-rsa/pki/private/${client_name}.key" /etc/openvpn/client/
	cp "/etc/easy-rsa/pki/issued/${client_name}.crt" /etc/openvpn/client/

	# Create client.ovpn file
	echo "${config}" | sed "s/REMOTE_IP/${remote_IP}/g" \
		| sed $'/<\/ca>/{e cat /etc/openvpn/server/ca.crt\n}' \
		| sed $'/</cert>/{e cat /etc/openvpn/client/${client_name}.crt\n}' \
		| sed $'/</key>/{e cat /etc/openvpn/client/${client_name}.key\n}' \
		| sed $'/</tls-crypt>/{e cat /etc/openvpn/server/ta.key\n}' \
		> "/etc/openvpn/client/${client_name}.ovpn"
	
	return 0
}

readonly config="# OpenVPN client config

client
dev tun
remote REMOTE_IP 1194 udp
resolv-retry infinite
nobind
persist-key
persist-tun
verb 4

auth SHA512
auth-nocache
cipher AES-256-GCM

tls-client
tls-version-min 1.3
tls-cipher TLS-DHE-RSA-WITH-AES-128-GCM-SHA256

remote-cert-tls server

###
###     Keys and certificates
###

# Server cert (ca.crt)
<ca>
</ca>

# Client cert (client.crt)
<cert>
</cert>

# Client key (client.key)
<key>
</key>

# Shared-secret key (ta.key)
<tls-crypt>
</tls-crypt>
"

main "${@}"; exit
